//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudEmployee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTable
    {
        public int Addid { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public int Empid { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
